### ISSUE TITLE
[DOC] Hint on how to change color scheme

### ISSUE THREAD

**Issue by GradedJestRisk** [maahl/pg_explain_lexer#1]
I was delighted when I saw the documentation screenshots, but was disappointed on the first local run.
The cyan on index name turns out unreadable. 
![image](https://user-images.githubusercontent.com/37769607/125904807-cbdd429b-b57f-4cc8-8549-4e5fd7e7abe4.png)

I can't figure out if the color theme comes from the terminal / multiplexer / pygmentize
I use terminator + zsh + oh-my-zsh with theme powerlevel10k/powerlevel10k

Can you supply a hint on this in documentation, even if it is out of scope of pg_explain_lexer.py?

**Comment by maahl** [comment]
Hi, the color scheme comes from pygmentize styles, you can change it by passing the style argument to it:

```sh
pygmentize -O style=autumn -l ~/projects/pg_explain_lexer/pg_explain_lexer.py:PgExplainLexer -x <(psql -c "EXPLAIN ANALYZE SELECT * from pg_class")
pygmentize -O style=default -l ~/projects/pg_explain_lexer/pg_explain_lexer.py:PgExplainLexer -x <(psql -c "EXPLAIN ANALYZE SELECT * from pg_class")
pygmentize -O style=colorful -l ~/projects/pg_explain_lexer/pg_explain_lexer.py:PgExplainLexer -x <(psql -c "EXPLAIN ANALYZE SELECT * from pg_class")
```

![image](https://user-images.githubusercontent.com/2880719/125911085-c7a03caa-20ed-4ed4-a054-2c84fda2963a.png)

You can view the list of available pygments style by running this in python:
```py
>>> from pygments.styles import get_all_styles
>>> print(list(get_all_styles()))
```
The documentation for pygments styles is [here](https://pygments.org/docs/styles/).
I'll update the readme with an example for this this weekend, thanks for the suggestion!

**Comment by octo-topi** [comment]
Just what I need :pray:

**Comment by GradedJestRisk** [comment]
Just what I need :pray: 
Many thanks !
