### ISSUE TITLE
[DOC] Add use sample out of pg CLI 

### ISSUE THREAD

**Issue by GradedJestRisk** [maahl/pg_explain_lexer#2]
Your [blog post](https://maahl.net/pg_explain_lexer) show several use-case not found in README.md, which is great. 

I'm especially interested on invoking it out of CLI, eg. in combination 
- with [docker logs](https://github.com/GradedJestRisk/db-training/blob/master/RDBMS/PostgreSQL/performance/use-index-luke/explain/package.json#L8) 
- on top of postgresql logs with [auto-explain](https://github.com/GradedJestRisk/db-training/blob/master/RDBMS/PostgreSQL/performance/use-index-luke/explain/docker-compose.yml#L15) activated

I don't care about overhead issues, as it's for development purpose.

**Comment by maahl** [comment]
I suppose the easiest would be to pass the output of your logs to a wrapper script that puts the log line through pygmentize if it's part of an explain result, and spits it out unchanged otherwise.

We then need a reliable way to determine whether we're in the middle of an explain result or not. You'd probably set a flag when encountering the `QUERY PLAN` string, I'm not sure how to detect the end of a query plan though. It might be safe to assume that a line containing only ` Execution Time: 0.251 ms` marks the end of the query plan.

I'll see this weekend if I can get a simple script working, or if you do get one, p;lease post it here :)

**Comment by maahl** [comment]
I added a script that parses postgresql's log file and colorizes auto_explain's output, it's a bit rough around the edges but should be usable. Let me know if that suits your needs!

**Comment by GradedJestRisk** [comment]
It works like a charm on a local file :tada: Many thanks for so much effort !
Hope your work will be made available in  `pg_cli` some day, as refered to [here](https://github.com/dbcli/pgcli/issues/416)


But.. for some reason I can't figure, `docker logs -tf` does not behave as `tail -f`.
The following command fails (it fills up the screen  with whitespaces)
`docker logs --tail 50 database | ~/scripts/colorize_plans_in_logs.py --sql-style=colorful --explain-style=autumn`

I tried different approaches, but none of them works out of the box :roll_eyes: 
Would you mind having a look to check if your script can be made to work with `docker logs -tf` ?

## Use docker log files
I tried to run it in on the underlying file, but as docker default driver is JSON, it failed
`sudo tail -f /var/lib/docker/containers/<ID>/<ID>-json.log | ~/scripts/colorize_plans_in_logs.py --sql-style=colorful --explain-style=autumn`

The log below is not colorized
``` json
{"log":"2021-07-19 14:34:16.284 UTC [1] LOG:  database system is ready to accept connections\n","stream":"stderr","time":"2021-07-19T14:34:16.28493963Z"}
{"log":"2021-07-19 14:35:39.543 UTC [55] LOG:  statement: select * from pg_class;\n","stream":"stderr","time":"2021-07-19T14:35:39.543949042Z"}
{"log":"2021-07-19 14:35:39.550 UTC [55] LOG:  duration: 3.981 ms  plan:\n","stream":"stderr","time":"2021-07-19T14:35:39.551006077Z"}
{"log":"\u0009Query Text: select * from pg_class;\n","stream":"stderr","time":"2021-07-19T14:35:39.551037072Z"}
{"log":"\u0009Seq Scan on pg_class  (cost=0.00..16.86 rows=386 width=265) (actual time=0.013..0.146 rows=386 loops=1)\n","stream":"stderr","time":"2021-07-19T14:35:39.551048621Z"}
{"log":"2021-07-19 14:44:34.674 UTC [88] LOG:  statement: show log_destination ;\n","stream":"stderr","time":"2021-07-19T14:44:34.674325771Z"}
{"log":"2021-07-19 14:44:54.283 UTC [88] LOG:  statement: show log_directory ;\n","stream":"stderr","time":"2021-07-19T14:44:54.2841618Z"
```
## Run it inside the container
I thought about running the script inside the container, but that would require some python setup as database image is alpine, and I would like to keep things simple

## Expose logs in volume
Why not storing raw logs in a docker volume ? Well, to do that you need to build a custom image according to [SO](https://stackoverflow.com/questions/48862633/how-to-setup-volume-for-postgres-log-folder-permission-denied-error)

**Comment by maahl** [comment]
Hey, it seems that docker or the postgres image (assuming you use the official one) outputs the logs to stderr for some reason (as indicated in the json logs, that's how i got the clue of what was going on :) ).
so redirecting stderr to stdout with something like `docker logs -f some-postgres  2>&1 | ~/projects/pg_explain_lexer/colorize_plans_in_logs.py --sql-style=colorful --explain-style=autumn` did the trick for me, let me know if that solves your issue!

As for integration with pgcli, that would be pretty cool indeed, I'll take a look this week and see how easy that would be. Thanks for the pointer!

**Comment by GradedJestRisk** [comment]
Awesome ! It works
![image](https://user-images.githubusercontent.com/37769607/126360178-6217634d-2a16-4397-a4dc-79d9d052b50a.png)

>As for integration with pgcli, that would be pretty cool indeed, I'll take a look this week and see how easy that would be. Thanks for the pointer!

Well, as you'll see, https://github.com/deather thought about it a few month ago, so that would be very cool !
