### ISSUE TITLE
LICENCE to propose this lexer to pygments

### ISSUE THREAD

**Issue by anayrat** [maahl/pg_explain_lexer#3]
Hello Maxence !

I want to propose your lexer to pygments project,  I will have to make some changes.

I wonder if I can reuse your code ?

Thanks!

**Comment by maahl** [comment]
you're more than welcome to do so, thanks a lot for this!

**Comment by anayrat** [comment]
Thank you :)

**Comment by anayrat** [comment]
FTR https://github.com/pygments/pygments/pull/2398

**Comment by maahl** [comment]
thanks a lot, this is great :tada:
